<?php
/**
 * ACF field definitions for the Home page template.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

function starter_register_home_acf_fields() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group(
		array(
			'key'                   => 'group_starter_home',
			'title'                 => __( 'Home Page Content', 'starter-theme' ),
			'fields'                => array(
				array(
					'key'               => 'field_starter_home_hero_tab',
					'label'             => __( 'Hero', 'starter-theme' ),
					'name'              => '',
					'type'              => 'tab',
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_starter_home_hero_title',
					'label'             => __( 'Hero Title', 'starter-theme' ),
					'name'              => 'hero_title',
					'type'              => 'text',
					'required'          => 0,
				),
				array(
					'key'               => 'field_starter_home_hero_desc',
					'label'             => __( 'Hero Desc', 'starter-theme' ),
					'name'              => 'hero_desc',
					'type'              => 'wysiwyg',
					'tabs'              => 'all',
					'toolbar'           => 'basic',
					'media_upload'      => 0,
					'delay'             => 0,
				),
				array(
					'key'               => 'field_starter_home_hero_images',
					'label'             => __( 'Hero Images', 'starter-theme' ),
					'name'              => 'hero_images',
					'type'              => 'gallery',
					'return_format'     => 'array',
					'preview_size'      => 'medium',
					'insert'            => 'append',
					'library'           => 'all',
					'min'               => 0,
					'max'               => 3,
				),
				array(
					'key'               => 'field_starter_home_section_1_tab',
					'label'             => __( 'Section 1', 'starter-theme' ),
					'name'              => '',
					'type'              => 'tab',
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_starter_home_section_1_title',
					'label'             => __( 'Section 1 Title', 'starter-theme' ),
					'name'              => 'section_1_title',
					'type'              => 'text',
				),
				array(
					'key'               => 'field_starter_home_section_1_desc',
					'label'             => __( 'Section 1 Desc', 'starter-theme' ),
					'name'              => 'section_1_desc',
					'type'              => 'wysiwyg',
					'tabs'              => 'all',
					'toolbar'           => 'basic',
					'media_upload'      => 0,
					'delay'             => 0,
				),
				array(
					'key'               => 'field_starter_home_section_1_images',
					'label'             => __( 'Section 1 Images', 'starter-theme' ),
					'name'              => 'section_1_images',
					'type'              => 'gallery',
					'return_format'     => 'array',
					'preview_size'      => 'medium',
					'insert'            => 'append',
					'library'           => 'all',
					'min'               => 0,
					'max'               => 4,
				),
				array(
					'key'               => 'field_starter_home_section_2_tab',
					'label'             => __( 'Section 2', 'starter-theme' ),
					'name'              => '',
					'type'              => 'tab',
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_starter_home_section_2_title',
					'label'             => __( 'Section 2 Title', 'starter-theme' ),
					'name'              => 'section_2_title',
					'type'              => 'text',
				),
				array(
					'key'               => 'field_starter_home_section_2_desc',
					'label'             => __( 'Section 2 Desc', 'starter-theme' ),
					'name'              => 'section_2_desc',
					'type'              => 'wysiwyg',
					'tabs'              => 'all',
					'toolbar'           => 'basic',
					'media_upload'      => 0,
					'delay'             => 0,
				),
				array(
					'key'               => 'field_starter_home_section_3_tab',
					'label'             => __( 'Section 3', 'starter-theme' ),
					'name'              => '',
					'type'              => 'tab',
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_starter_home_section_3_hero',
					'label'             => __( 'Section 3 Hero', 'starter-theme' ),
					'name'              => 'section_3_hero',
					'type'              => 'image',
					'return_format'     => 'array',
					'preview_size'      => 'medium',
					'library'           => 'all',
				),
				array(
					'key'               => 'field_starter_home_section_3_title',
					'label'             => __( 'Section 3 Title', 'starter-theme' ),
					'name'              => 'section_3_title',
					'type'              => 'text',
				),
				array(
					'key'               => 'field_starter_home_section_3_images',
					'label'             => __( 'Section 3 Images', 'starter-theme' ),
					'name'              => 'section_3_images',
					'type'              => 'gallery',
					'return_format'     => 'array',
					'preview_size'      => 'medium',
					'insert'            => 'append',
					'library'           => 'all',
					'min'               => 0,
					'max'               => 3,
				),
				array(
					'key'               => 'field_starter_home_section_4_tab',
					'label'             => __( 'Section 4', 'starter-theme' ),
					'name'              => '',
					'type'              => 'tab',
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_starter_home_section_4_title',
					'label'             => __( 'Section 4 Title', 'starter-theme' ),
					'name'              => 'section_4_title',
					'type'              => 'text',
				),
				array(
					'key'               => 'field_starter_home_section_4_desc',
					'label'             => __( 'Section 4 Desc', 'starter-theme' ),
					'name'              => 'section_4_desc',
					'type'              => 'wysiwyg',
					'tabs'              => 'all',
					'toolbar'           => 'basic',
					'media_upload'      => 0,
					'delay'             => 0,
				),
				array(
					'key'               => 'field_starter_home_section_4_posts',
					'label'             => __( 'Section 4 Posts', 'starter-theme' ),
					'name'              => 'section_4_posts',
					'type'              => 'repeater',
					'layout'            => 'block',
					'button_label'      => __( 'Add Post Card', 'starter-theme' ),
					'collapsed'         => 'field_starter_home_section_4_post_title',
					'sub_fields'        => array(
						array(
							'key'           => 'field_starter_home_section_4_post_img',
							'label'         => __( 'Image', 'starter-theme' ),
							'name'          => 'img',
							'type'          => 'image',
							'return_format' => 'array',
							'preview_size'  => 'thumbnail',
							'library'       => 'all',
						),
						array(
							'key'           => 'field_starter_home_section_4_post_title',
							'label'         => __( 'Title', 'starter-theme' ),
							'name'          => 'title',
							'type'          => 'text',
						),
						array(
							'key'           => 'field_starter_home_section_4_post_desc',
							'label'         => __( 'Desc', 'starter-theme' ),
							'name'          => 'desc',
							'type'          => 'textarea',
							'rows'          => 3,
							'new_lines'     => '',
						),
						array(
							'key'           => 'field_starter_home_section_4_post_url',
							'label'         => __( 'Link', 'starter-theme' ),
							'name'          => 'url',
							'type'          => 'url',
							'instructions'  => __( 'Optional. Leave empty if this card should not have a button.', 'starter-theme' ),
						),
					),
				),
				array(
					'key'               => 'field_starter_home_form_tab',
					'label'             => __( 'Form', 'starter-theme' ),
					'name'              => '',
					'type'              => 'tab',
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_starter_home_form_title',
					'label'             => __( 'Form Title', 'starter-theme' ),
					'name'              => 'form_title',
					'type'              => 'text',
				),
				array(
					'key'               => 'field_starter_home_form_desc',
					'label'             => __( 'Form Desc', 'starter-theme' ),
					'name'              => 'form_desc',
					'type'              => 'wysiwyg',
					'tabs'              => 'all',
					'toolbar'           => 'basic',
					'media_upload'      => 0,
					'delay'             => 0,
				),
				array(
					'key'               => 'field_starter_home_form_desc2',
					'label'             => __( 'Form Desc2', 'starter-theme' ),
					'name'              => 'form_desc2',
					'type'              => 'wysiwyg',
					'tabs'              => 'all',
					'toolbar'           => 'basic',
					'media_upload'      => 0,
					'delay'             => 0,
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'page_template',
						'operator' => '==',
						'value'    => 'templates/home.php',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => array(),
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
		)
	);
}
add_action( 'acf/init', 'starter_register_home_acf_fields' );
